const FETCH_USER =  "FETCH_USER";
const INIT_USER = "INIT_USER";
const UPDATE_USER =  "UPDATE_USER";
const FETCH_IMAGE =  "FETCH_IMAGE";
const UPDATE_IMAGE =  "UPDATE_IMAGE";
const UPDATE_PAGI =  "UPDATE_PAGI";
const UPDATE_FILTER_DATE = "UPDATE_FILTER_DATE";
export {
    INIT_USER,
    FETCH_USER,
    UPDATE_USER,
    FETCH_IMAGE,
    UPDATE_IMAGE,
    UPDATE_FILTER_DATE,
    UPDATE_PAGI
}